version: 2.1

jobs:
  test-electron:
    parameters:
      electron_version:
        type: string
    docker:
      - image: electronjs/build:d09fd95029bd8c1c73069888231b29688ef385ed
    environment:
      DISPLAY: ':99.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-node_modules-{{ arch }}
      - run: npx yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: npx yarn add electron@<< parameters.electron_version >>
      - run: sh -e /etc/init.d/xvfb start
      - run: npx yarn test

  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npx yarn
      - run: npx semantic-release@19

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-electron:
          name: test-electron-12
          electron_version: ^12.0.0
      - release:
          requires:
            - test-electron-12
          filters:
            branches:
              only:
                - master
